# !!! THIS FILE IS GENERATED BY generate.py
# !!! DO NOT EDIT THIS FILE DIRECTLY

from __future__ import annotations

import dataclasses
import typing

import spess._backend as backend
from spess._json import Json, from_json, to_json
import spess.models as models
from spess._model_bases import date, datetime, Enum, Keyed
from spess._paged import Paged

__all__ = [
    'AcceptContract', 'CreateChart', 'CreateShipShipScan',
    'CreateShipSystemScan', 'CreateShipWaypointScan', 'CreateSurvey',
    'DeliverContract', 'DockShip', 'ErrorCodes', 'ExtractResources',
    'ExtractResourcesWithSurvey', 'FulfillContract', 'GetRepairShip',
    'GetScrapShip', 'InstallMount', 'InstallShipModule', 'Jettison',
    'JumpShip', 'MyAccount', 'MyFaction', 'NavigateShip',
    'NegotiateContract', 'OrbitShip', 'PatchShipNav', 'PurchaseCargo',
    'PurchaseShip', 'RefuelShip', 'Register', 'RemoveMount',
    'RemoveShipModule', 'RepairShip', 'ScrapShip', 'SellCargo',
    'ServerStatus', 'ShipRefine', 'SiphonResources', 'SupplyConstruction',
    'TransferCargo', 'WarpShip',
]

# spec_name: get-status.response
@dataclasses.dataclass
class ServerStatus:
    """Fetched status successfully."""

    # spec_name: get-status.response.stats
    @dataclasses.dataclass
    class Stats:
        __doc__ = ' '

        #: Number of registered agents in the game.
        agents: int
        #: Total number of ships in the game.
        ships: int
        #: Total number of systems in the game.
        systems: int
        #: Total number of waypoints in the game.
        waypoints: int
        #: Total number of accounts registered on the game server.
        accounts: int | None = None

        def to_json(self) -> Json:
            v = {
                'agents': to_json(self.agents),
                'ships': to_json(self.ships),
                'systems': to_json(self.systems),
                'waypoints': to_json(self.waypoints),
            }
            if self.accounts is not None:
                v['accounts'] = to_json(self.accounts)
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                agents = from_json(int, v['agents']),
                ships = from_json(int, v['ships']),
                systems = from_json(int, v['systems']),
                waypoints = from_json(int, v['waypoints']),
                accounts = from_json(int, v['accounts']) if 'accounts' in v else None,
            )

    # spec_name: get-status.response.health
    @dataclasses.dataclass
    class Health:
        __doc__ = ' '

        #: The date/time when the market was last updated.
        last_market_update: datetime | None = None

        def to_json(self) -> Json:
            v = {
            }
            if self.last_market_update is not None:
                v['lastMarketUpdate'] = to_json(self.last_market_update)
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                last_market_update = from_json(datetime, v['lastMarketUpdate']) if 'lastMarketUpdate' in v else None,
            )

    # spec_name: get-status.response.leaderboards
    @dataclasses.dataclass
    class Leaderboards:
        __doc__ = ' '

        # spec_name: get-status.response.leaderboards.mostCredits
        @dataclasses.dataclass
        class MostCredit:
            __doc__ = ' '

            #: Symbol of the agent.
            agent_symbol: str
            #: Amount of credits.
            credits: int

            def to_json(self) -> Json:
                v = {
                    'agentSymbol': to_json(self.agent_symbol),
                    'credits': to_json(self.credits),
                }
                return v

            @classmethod
            def from_json(cls, v: Json) -> typing.Self:
                if not isinstance(v, dict):
                    raise TypeError(type(v))
                return cls(
                    agent_symbol = from_json(str, v['agentSymbol']),
                    credits = from_json(int, v['credits']),
                )

        # spec_name: get-status.response.leaderboards.mostSubmittedCharts
        @dataclasses.dataclass
        class MostSubmittedChart:
            __doc__ = ' '

            #: Symbol of the agent.
            agent_symbol: str
            #: Amount of charts done by the agent.
            chart_count: int

            def to_json(self) -> Json:
                v = {
                    'agentSymbol': to_json(self.agent_symbol),
                    'chartCount': to_json(self.chart_count),
                }
                return v

            @classmethod
            def from_json(cls, v: Json) -> typing.Self:
                if not isinstance(v, dict):
                    raise TypeError(type(v))
                return cls(
                    agent_symbol = from_json(str, v['agentSymbol']),
                    chart_count = from_json(int, v['chartCount']),
                )

        #: Top agents with the most credits.
        most_credits: list[ServerStatus.Leaderboards.MostCredit]
        #: Top agents with the most charted submitted.
        most_submitted_charts: list[ServerStatus.Leaderboards.MostSubmittedChart]

        def to_json(self) -> Json:
            v = {
                'mostCredits': to_json(self.most_credits),
                'mostSubmittedCharts': to_json(self.most_submitted_charts),
            }
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                most_credits = from_json(list[ServerStatus.Leaderboards.MostCredit], v['mostCredits']),
                most_submitted_charts = from_json(list[ServerStatus.Leaderboards.MostSubmittedChart], v['mostSubmittedCharts']),
            )

    # spec_name: get-status.response.serverResets
    @dataclasses.dataclass
    class ServerResets:
        __doc__ = ' '

        #: The date and time when the game server will reset.
        next: datetime
        #: How often we intend to reset the game server.
        frequency: str

        def to_json(self) -> Json:
            v = {
                'next': to_json(self.next),
                'frequency': to_json(self.frequency),
            }
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                next = from_json(datetime, v['next']),
                frequency = from_json(str, v['frequency']),
            )

    # spec_name: get-status.response.announcements
    @dataclasses.dataclass
    class Announcement:
        __doc__ = ' '

        title: str
        body: str

        def to_json(self) -> Json:
            v = {
                'title': to_json(self.title),
                'body': to_json(self.body),
            }
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                title = from_json(str, v['title']),
                body = from_json(str, v['body']),
            )

    # spec_name: get-status.response.links
    @dataclasses.dataclass
    class Link:
        __doc__ = ' '

        name: str
        url: str

        def to_json(self) -> Json:
            v = {
                'name': to_json(self.name),
                'url': to_json(self.url),
            }
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                name = from_json(str, v['name']),
                url = from_json(str, v['url']),
            )

    #: The current status of the game server.
    status: str
    #: The current version of the API.
    version: str
    #: The date when the game server was last reset.
    reset_date: date
    description: str
    stats: ServerStatus.Stats
    health: ServerStatus.Health
    leaderboards: ServerStatus.Leaderboards
    server_resets: ServerStatus.ServerResets
    announcements: list[ServerStatus.Announcement]
    links: list[ServerStatus.Link]

    def to_json(self) -> Json:
        v = {
            'status': to_json(self.status),
            'version': to_json(self.version),
            'resetDate': to_json(self.reset_date),
            'description': to_json(self.description),
            'stats': to_json(self.stats),
            'health': to_json(self.health),
            'leaderboards': to_json(self.leaderboards),
            'serverResets': to_json(self.server_resets),
            'announcements': to_json(self.announcements),
            'links': to_json(self.links),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            status = from_json(str, v['status']),
            version = from_json(str, v['version']),
            reset_date = from_json(date, v['resetDate']),
            description = from_json(str, v['description']),
            stats = from_json(ServerStatus.Stats, v['stats']),
            health = from_json(ServerStatus.Health, v['health']),
            leaderboards = from_json(ServerStatus.Leaderboards, v['leaderboards']),
            server_resets = from_json(ServerStatus.ServerResets, v['serverResets']),
            announcements = from_json(list[ServerStatus.Announcement], v['announcements']),
            links = from_json(list[ServerStatus.Link], v['links']),
        )

# spec_name: get-error-codes.response
@dataclasses.dataclass
class ErrorCodes:
    """Fetched error codes successfully."""

    # spec_name: get-error-codes.response.errorCodes
    @dataclasses.dataclass
    class ErrorCode:
        __doc__ = ' '

        code: int
        name: str

        def to_json(self) -> Json:
            v = {
                'code': to_json(self.code),
                'name': to_json(self.name),
            }
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                code = from_json(int, v['code']),
                name = from_json(str, v['name']),
            )

    error_codes: list[ErrorCodes.ErrorCode]

    def to_json(self) -> Json:
        v = {
            'errorCodes': to_json(self.error_codes),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            error_codes = from_json(list[ErrorCodes.ErrorCode], v['errorCodes']),
        )

# spec_name: supply-construction.response
@dataclasses.dataclass
class SupplyConstruction:
    """Successfully supplied construction site."""

    #: The construction details of a waypoint.
    construction: models.Construction
    #: Ship cargo details.
    cargo: models.ShipCargo

    def to_json(self) -> Json:
        v = {
            'construction': to_json(self.construction),
            'cargo': to_json(self.cargo),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            construction = from_json(models.Construction, v['construction']),
            cargo = from_json(models.ShipCargo, v['cargo']),
        )

# spec_name: accept-contract.response
@dataclasses.dataclass
class AcceptContract:
    """Successfully accepted contract."""

    #: Contract details.
    contract: models.Contract
    #: Agent details.
    agent: models.Agent

    def to_json(self) -> Json:
        v = {
            'contract': to_json(self.contract),
            'agent': to_json(self.agent),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            contract = from_json(models.Contract, v['contract']),
            agent = from_json(models.Agent, v['agent']),
        )

# spec_name: fulfill-contract.response
@dataclasses.dataclass
class FulfillContract:
    """Successfully fulfilled a contract."""

    #: Contract details.
    contract: models.Contract
    #: Agent details.
    agent: models.Agent

    def to_json(self) -> Json:
        v = {
            'contract': to_json(self.contract),
            'agent': to_json(self.agent),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            contract = from_json(models.Contract, v['contract']),
            agent = from_json(models.Agent, v['agent']),
        )

# spec_name: deliver-contract.response
@dataclasses.dataclass
class DeliverContract:
    """Successfully delivered cargo to contract."""

    #: Contract details.
    contract: models.Contract
    #: Ship cargo details.
    cargo: models.ShipCargo

    def to_json(self) -> Json:
        v = {
            'contract': to_json(self.contract),
            'cargo': to_json(self.cargo),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            contract = from_json(models.Contract, v['contract']),
            cargo = from_json(models.ShipCargo, v['cargo']),
        )

# spec_name: get-my-factions.response
@dataclasses.dataclass
class MyFaction:
    __doc__ = ' '

    symbol: models.FactionSymbol
    reputation: int

    def to_json(self) -> Json:
        v = {
            'symbol': to_json(self.symbol),
            'reputation': to_json(self.reputation),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            symbol = from_json(models.FactionSymbol, v['symbol']),
            reputation = from_json(int, v['reputation']),
        )

# spec_name: purchase-ship.response
@dataclasses.dataclass
class PurchaseShip:
    """Purchased ship successfully."""

    #: Ship details.
    ship: models.Ship
    #: Agent details.
    agent: models.Agent
    #: Results of a transaction with a shipyard.
    transaction: models.ShipyardTransaction

    def to_json(self) -> Json:
        v = {
            'ship': to_json(self.ship),
            'agent': to_json(self.agent),
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            ship = from_json(models.Ship, v['ship']),
            agent = from_json(models.Agent, v['agent']),
            transaction = from_json(models.ShipyardTransaction, v['transaction']),
        )

# spec_name: get-my-account.response
@dataclasses.dataclass
class MyAccount:
    """Default Response"""

    # spec_name: get-my-account.response.account
    @dataclasses.dataclass
    class Account:
        __doc__ = ' '

        id: str
        email: str
        created_at: datetime
        token: str | None = None

        def to_json(self) -> Json:
            v = {
                'id': to_json(self.id),
                'email': to_json(self.email),
                'createdAt': to_json(self.created_at),
            }
            if self.token is not None:
                v['token'] = to_json(self.token)
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                id = from_json(str, v['id']),
                email = from_json(str, v['email']),
                created_at = from_json(datetime, v['createdAt']),
                token = from_json(str, v['token']) if 'token' in v else None,
            )

    account: MyAccount.Account

    def to_json(self) -> Json:
        v = {
            'account': to_json(self.account),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            account = from_json(MyAccount.Account, v['account']),
        )

# spec_name: create-chart.response
@dataclasses.dataclass
class CreateChart:
    """Successfully charted waypoint."""

    #: The chart of a system or waypoint, which makes the location
    #: visible to other agents.
    chart: models.Chart
    #: A waypoint is a location that ships can travel to such as a
    #: Planet, Moon or Space Station.
    waypoint: models.Waypoint
    #: Result of a chart transaction.
    transaction: models.ChartTransaction
    #: Agent details.
    agent: models.Agent

    def to_json(self) -> Json:
        v = {
            'chart': to_json(self.chart),
            'waypoint': to_json(self.waypoint),
            'transaction': to_json(self.transaction),
            'agent': to_json(self.agent),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            chart = from_json(models.Chart, v['chart']),
            waypoint = from_json(models.Waypoint, v['waypoint']),
            transaction = from_json(models.ChartTransaction, v['transaction']),
            agent = from_json(models.Agent, v['agent']),
        )

# spec_name: negotiate-contract.response
@dataclasses.dataclass
class NegotiateContract:
    """Successfully negotiated a new contract."""

    #: Contract details.
    contract: models.Contract

    def to_json(self) -> Json:
        v = {
            'contract': to_json(self.contract),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            contract = from_json(models.Contract, v['contract']),
        )

# spec_name: dock-ship.response
@dataclasses.dataclass
class DockShip:
    """The ship has successfully docked at its current location."""

    #: The navigation information of the ship.
    nav: models.ShipNav

    def to_json(self) -> Json:
        v = {
            'nav': to_json(self.nav),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            nav = from_json(models.ShipNav, v['nav']),
        )

# spec_name: extract-resources.response
@dataclasses.dataclass
class ExtractResources:
    """Successfully extracted resources."""

    #: Extraction details.
    extraction: models.Extraction
    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: Ship cargo details.
    cargo: models.ShipCargo
    events: list[models.ShipConditionEvent]
    modifiers: list[models.WaypointModifierInfo] | None = None

    def to_json(self) -> Json:
        v = {
            'extraction': to_json(self.extraction),
            'cooldown': to_json(self.cooldown),
            'cargo': to_json(self.cargo),
            'events': to_json(self.events),
        }
        if self.modifiers is not None:
            v['modifiers'] = to_json(self.modifiers)
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            extraction = from_json(models.Extraction, v['extraction']),
            cooldown = from_json(models.Cooldown, v['cooldown']),
            cargo = from_json(models.ShipCargo, v['cargo']),
            events = from_json(list[models.ShipConditionEvent], v['events']),
            modifiers = from_json(list[models.WaypointModifierInfo], v['modifiers']) if 'modifiers' in v else None,
        )

# spec_name: extract-resources-with-survey.response
@dataclasses.dataclass
class ExtractResourcesWithSurvey:
    """Successfully extracted resources."""

    #: Extraction details.
    extraction: models.Extraction
    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: Ship cargo details.
    cargo: models.ShipCargo
    events: list[models.ShipConditionEvent]
    modifiers: list[models.WaypointModifierInfo] | None = None

    def to_json(self) -> Json:
        v = {
            'extraction': to_json(self.extraction),
            'cooldown': to_json(self.cooldown),
            'cargo': to_json(self.cargo),
            'events': to_json(self.events),
        }
        if self.modifiers is not None:
            v['modifiers'] = to_json(self.modifiers)
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            extraction = from_json(models.Extraction, v['extraction']),
            cooldown = from_json(models.Cooldown, v['cooldown']),
            cargo = from_json(models.ShipCargo, v['cargo']),
            events = from_json(list[models.ShipConditionEvent], v['events']),
            modifiers = from_json(list[models.WaypointModifierInfo], v['modifiers']) if 'modifiers' in v else None,
        )

# spec_name: jettison.response
@dataclasses.dataclass
class Jettison:
    """Jettison successful."""

    #: Ship cargo details.
    cargo: models.ShipCargo

    def to_json(self) -> Json:
        v = {
            'cargo': to_json(self.cargo),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cargo = from_json(models.ShipCargo, v['cargo']),
        )

# spec_name: jump-ship.response
@dataclasses.dataclass
class JumpShip:
    """Jump successful."""

    #: The navigation information of the ship.
    nav: models.ShipNav
    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: Result of a transaction with a market.
    transaction: models.MarketTransaction
    #: Agent details.
    agent: models.Agent

    def to_json(self) -> Json:
        v = {
            'nav': to_json(self.nav),
            'cooldown': to_json(self.cooldown),
            'transaction': to_json(self.transaction),
            'agent': to_json(self.agent),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            nav = from_json(models.ShipNav, v['nav']),
            cooldown = from_json(models.Cooldown, v['cooldown']),
            transaction = from_json(models.MarketTransaction, v['transaction']),
            agent = from_json(models.Agent, v['agent']),
        )

# spec_name: create-ship-system-scan.response
@dataclasses.dataclass
class CreateShipSystemScan:
    """Successfully scanned for nearby systems."""

    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: List of scanned systems.
    systems: list[models.ScannedSystem]

    def to_json(self) -> Json:
        v = {
            'cooldown': to_json(self.cooldown),
            'systems': to_json(self.systems),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cooldown = from_json(models.Cooldown, v['cooldown']),
            systems = from_json(list[models.ScannedSystem], v['systems']),
        )

# spec_name: create-ship-waypoint-scan.response
@dataclasses.dataclass
class CreateShipWaypointScan:
    """Successfully scanned for nearby waypoints."""

    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: List of scanned waypoints.
    waypoints: list[models.ScannedWaypoint]

    def to_json(self) -> Json:
        v = {
            'cooldown': to_json(self.cooldown),
            'waypoints': to_json(self.waypoints),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cooldown = from_json(models.Cooldown, v['cooldown']),
            waypoints = from_json(list[models.ScannedWaypoint], v['waypoints']),
        )

# spec_name: create-ship-ship-scan.response
@dataclasses.dataclass
class CreateShipShipScan:
    """Successfully scanned for nearby ships."""

    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: List of scanned ships.
    ships: list[models.ScannedShip]

    def to_json(self) -> Json:
        v = {
            'cooldown': to_json(self.cooldown),
            'ships': to_json(self.ships),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cooldown = from_json(models.Cooldown, v['cooldown']),
            ships = from_json(list[models.ScannedShip], v['ships']),
        )

# spec_name: scrap-ship.response
@dataclasses.dataclass
class ScrapShip:
    """Ship scrapped successfully."""

    #: Agent details.
    agent: models.Agent
    #: Result of a scrap transaction.
    transaction: models.ScrapTransaction

    def to_json(self) -> Json:
        v = {
            'agent': to_json(self.agent),
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            agent = from_json(models.Agent, v['agent']),
            transaction = from_json(models.ScrapTransaction, v['transaction']),
        )

# spec_name: get-scrap-ship.response
@dataclasses.dataclass
class GetScrapShip:
    """Successfully retrieved the amount of value that will be
    returned when scrapping a ship.
    """

    #: Result of a scrap transaction.
    transaction: models.ScrapTransaction

    def to_json(self) -> Json:
        v = {
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            transaction = from_json(models.ScrapTransaction, v['transaction']),
        )

# spec_name: navigate-ship.response
@dataclasses.dataclass
class NavigateShip:
    """The successful transit information including the route
    details and changes to ship fuel. The route includes the expected
    time of arrival.
    """

    #: The navigation information of the ship.
    nav: models.ShipNav
    #: Details of the ship's fuel tanks including how much fuel was
    #: consumed during the last transit or action.
    fuel: models.ShipFuel
    events: list[models.ShipConditionEvent]

    def to_json(self) -> Json:
        v = {
            'nav': to_json(self.nav),
            'fuel': to_json(self.fuel),
            'events': to_json(self.events),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            nav = from_json(models.ShipNav, v['nav']),
            fuel = from_json(models.ShipFuel, v['fuel']),
            events = from_json(list[models.ShipConditionEvent], v['events']),
        )

# spec_name: warp-ship.response
@dataclasses.dataclass
class WarpShip:
    """The successful transit information including the route
    details and changes to ship fuel. The route includes the expected
    time of arrival.
    """

    #: The navigation information of the ship.
    nav: models.ShipNav
    #: Details of the ship's fuel tanks including how much fuel was
    #: consumed during the last transit or action.
    fuel: models.ShipFuel
    events: list[models.ShipConditionEvent]

    def to_json(self) -> Json:
        v = {
            'nav': to_json(self.nav),
            'fuel': to_json(self.fuel),
            'events': to_json(self.events),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            nav = from_json(models.ShipNav, v['nav']),
            fuel = from_json(models.ShipFuel, v['fuel']),
            events = from_json(list[models.ShipConditionEvent], v['events']),
        )

# spec_name: orbit-ship.response
@dataclasses.dataclass
class OrbitShip:
    """The ship has successfully moved into orbit at its current
    location.
    """

    #: The navigation information of the ship.
    nav: models.ShipNav

    def to_json(self) -> Json:
        v = {
            'nav': to_json(self.nav),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            nav = from_json(models.ShipNav, v['nav']),
        )

# spec_name: purchase-cargo.response
@dataclasses.dataclass
class PurchaseCargo:
    """Purchased goods successfully."""

    #: Ship cargo details.
    cargo: models.ShipCargo
    #: Result of a transaction with a market.
    transaction: models.MarketTransaction
    #: Agent details.
    agent: models.Agent

    def to_json(self) -> Json:
        v = {
            'cargo': to_json(self.cargo),
            'transaction': to_json(self.transaction),
            'agent': to_json(self.agent),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cargo = from_json(models.ShipCargo, v['cargo']),
            transaction = from_json(models.MarketTransaction, v['transaction']),
            agent = from_json(models.Agent, v['agent']),
        )

# spec_name: ship-refine.response
@dataclasses.dataclass
class ShipRefine:
    """The ship has successfully refined goods."""

    # spec_name: ship-refine.response.produced
    @dataclasses.dataclass
    class ProducedItem:
        __doc__ = ' '

        #: The good's symbol.
        trade_symbol: models.TradeSymbol
        #: Amount of units of the good.
        units: int

        def to_json(self) -> Json:
            v = {
                'tradeSymbol': to_json(self.trade_symbol),
                'units': to_json(self.units),
            }
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                trade_symbol = from_json(models.TradeSymbol, v['tradeSymbol']),
                units = from_json(int, v['units']),
            )

    # spec_name: ship-refine.response.consumed
    @dataclasses.dataclass
    class ConsumedItem:
        __doc__ = ' '

        #: The good's symbol.
        trade_symbol: models.TradeSymbol
        #: Amount of units of the good.
        units: int

        def to_json(self) -> Json:
            v = {
                'tradeSymbol': to_json(self.trade_symbol),
                'units': to_json(self.units),
            }
            return v

        @classmethod
        def from_json(cls, v: Json) -> typing.Self:
            if not isinstance(v, dict):
                raise TypeError(type(v))
            return cls(
                trade_symbol = from_json(models.TradeSymbol, v['tradeSymbol']),
                units = from_json(int, v['units']),
            )

    #: Ship cargo details.
    cargo: models.ShipCargo
    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: Goods that were produced by this refining process.
    produced: list[ShipRefine.ProducedItem]
    #: Goods that were consumed during this refining process.
    consumed: list[ShipRefine.ConsumedItem]

    def to_json(self) -> Json:
        v = {
            'cargo': to_json(self.cargo),
            'cooldown': to_json(self.cooldown),
            'produced': to_json(self.produced),
            'consumed': to_json(self.consumed),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cargo = from_json(models.ShipCargo, v['cargo']),
            cooldown = from_json(models.Cooldown, v['cooldown']),
            produced = from_json(list[ShipRefine.ProducedItem], v['produced']),
            consumed = from_json(list[ShipRefine.ConsumedItem], v['consumed']),
        )

# spec_name: refuel-ship.response
@dataclasses.dataclass
class RefuelShip:
    """Refueled successfully."""

    #: Agent details.
    agent: models.Agent
    #: Details of the ship's fuel tanks including how much fuel was
    #: consumed during the last transit or action.
    fuel: models.ShipFuel
    #: Result of a transaction with a market.
    transaction: models.MarketTransaction
    #: Ship cargo details.
    cargo: models.ShipCargo | None = None

    def to_json(self) -> Json:
        v = {
            'agent': to_json(self.agent),
            'fuel': to_json(self.fuel),
            'transaction': to_json(self.transaction),
        }
        if self.cargo is not None:
            v['cargo'] = to_json(self.cargo)
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            agent = from_json(models.Agent, v['agent']),
            fuel = from_json(models.ShipFuel, v['fuel']),
            transaction = from_json(models.MarketTransaction, v['transaction']),
            cargo = from_json(models.ShipCargo, v['cargo']) if 'cargo' in v else None,
        )

# spec_name: repair-ship.response
@dataclasses.dataclass
class RepairShip:
    """Ship repaired successfully."""

    #: Agent details.
    agent: models.Agent
    #: Ship details.
    ship: models.Ship
    #: Result of a repair transaction.
    transaction: models.RepairTransaction

    def to_json(self) -> Json:
        v = {
            'agent': to_json(self.agent),
            'ship': to_json(self.ship),
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            agent = from_json(models.Agent, v['agent']),
            ship = from_json(models.Ship, v['ship']),
            transaction = from_json(models.RepairTransaction, v['transaction']),
        )

# spec_name: get-repair-ship.response
@dataclasses.dataclass
class GetRepairShip:
    """Successfully retrieved the cost of repairing a ship."""

    #: Result of a repair transaction.
    transaction: models.RepairTransaction

    def to_json(self) -> Json:
        v = {
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            transaction = from_json(models.RepairTransaction, v['transaction']),
        )

# spec_name: sell-cargo.response
@dataclasses.dataclass
class SellCargo:
    """Cargo was successfully sold."""

    #: Ship cargo details.
    cargo: models.ShipCargo
    #: Result of a transaction with a market.
    transaction: models.MarketTransaction
    #: Agent details.
    agent: models.Agent

    def to_json(self) -> Json:
        v = {
            'cargo': to_json(self.cargo),
            'transaction': to_json(self.transaction),
            'agent': to_json(self.agent),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cargo = from_json(models.ShipCargo, v['cargo']),
            transaction = from_json(models.MarketTransaction, v['transaction']),
            agent = from_json(models.Agent, v['agent']),
        )

# spec_name: siphon-resources.response
@dataclasses.dataclass
class SiphonResources:
    """Siphon successful."""

    #: Siphon details.
    siphon: models.Siphon
    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: Ship cargo details.
    cargo: models.ShipCargo
    events: list[models.ShipConditionEvent]

    def to_json(self) -> Json:
        v = {
            'siphon': to_json(self.siphon),
            'cooldown': to_json(self.cooldown),
            'cargo': to_json(self.cargo),
            'events': to_json(self.events),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            siphon = from_json(models.Siphon, v['siphon']),
            cooldown = from_json(models.Cooldown, v['cooldown']),
            cargo = from_json(models.ShipCargo, v['cargo']),
            events = from_json(list[models.ShipConditionEvent], v['events']),
        )

# spec_name: create-survey.response
@dataclasses.dataclass
class CreateSurvey:
    """Surveys has been created."""

    #: A cooldown is a period of time in which a ship cannot perform
    #: certain actions.
    cooldown: models.Cooldown
    #: Surveys created by this action.
    surveys: list[models.Survey]

    def to_json(self) -> Json:
        v = {
            'cooldown': to_json(self.cooldown),
            'surveys': to_json(self.surveys),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cooldown = from_json(models.Cooldown, v['cooldown']),
            surveys = from_json(list[models.Survey], v['surveys']),
        )

# spec_name: transfer-cargo.response
@dataclasses.dataclass
class TransferCargo:
    """Cargo transferred successfully."""

    #: Ship cargo details.
    cargo: models.ShipCargo
    #: Ship cargo details.
    target_cargo: models.ShipCargo

    def to_json(self) -> Json:
        v = {
            'cargo': to_json(self.cargo),
            'targetCargo': to_json(self.target_cargo),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            cargo = from_json(models.ShipCargo, v['cargo']),
            target_cargo = from_json(models.ShipCargo, v['targetCargo']),
        )

# spec_name: install-ship-module.response
@dataclasses.dataclass
class InstallShipModule:
    """Successfully installed the module on the ship."""

    #: Agent details.
    agent: models.Agent
    modules: list[models.ShipModule]
    #: Ship cargo details.
    cargo: models.ShipCargo
    #: Result of a transaction for a ship modification, such as
    #: installing a mount or a module.
    transaction: models.ShipModificationTransaction

    def to_json(self) -> Json:
        v = {
            'agent': to_json(self.agent),
            'modules': to_json(self.modules),
            'cargo': to_json(self.cargo),
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            agent = from_json(models.Agent, v['agent']),
            modules = from_json(list[models.ShipModule], v['modules']),
            cargo = from_json(models.ShipCargo, v['cargo']),
            transaction = from_json(models.ShipModificationTransaction, v['transaction']),
        )

# spec_name: remove-ship-module.response
@dataclasses.dataclass
class RemoveShipModule:
    """Successfully removed the module from the ship."""

    #: Agent details.
    agent: models.Agent
    modules: list[models.ShipModule]
    #: Ship cargo details.
    cargo: models.ShipCargo
    #: Result of a transaction for a ship modification, such as
    #: installing a mount or a module.
    transaction: models.ShipModificationTransaction

    def to_json(self) -> Json:
        v = {
            'agent': to_json(self.agent),
            'modules': to_json(self.modules),
            'cargo': to_json(self.cargo),
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            agent = from_json(models.Agent, v['agent']),
            modules = from_json(list[models.ShipModule], v['modules']),
            cargo = from_json(models.ShipCargo, v['cargo']),
            transaction = from_json(models.ShipModificationTransaction, v['transaction']),
        )

# spec_name: install-mount.response
@dataclasses.dataclass
class InstallMount:
    """Successfully installed the mount."""

    #: Agent details.
    agent: models.Agent
    #: List of installed mounts after the installation of the new
    #: mount.
    mounts: list[models.ShipMount]
    #: Ship cargo details.
    cargo: models.ShipCargo
    #: Result of a transaction for a ship modification, such as
    #: installing a mount or a module.
    transaction: models.ShipModificationTransaction

    def to_json(self) -> Json:
        v = {
            'agent': to_json(self.agent),
            'mounts': to_json(self.mounts),
            'cargo': to_json(self.cargo),
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            agent = from_json(models.Agent, v['agent']),
            mounts = from_json(list[models.ShipMount], v['mounts']),
            cargo = from_json(models.ShipCargo, v['cargo']),
            transaction = from_json(models.ShipModificationTransaction, v['transaction']),
        )

# spec_name: remove-mount.response
@dataclasses.dataclass
class RemoveMount:
    """Successfully removed the mount."""

    #: Agent details.
    agent: models.Agent
    #: List of installed mounts after the removal of the selected
    #: mount.
    mounts: list[models.ShipMount]
    #: Ship cargo details.
    cargo: models.ShipCargo
    #: Result of a transaction for a ship modification, such as
    #: installing a mount or a module.
    transaction: models.ShipModificationTransaction

    def to_json(self) -> Json:
        v = {
            'agent': to_json(self.agent),
            'mounts': to_json(self.mounts),
            'cargo': to_json(self.cargo),
            'transaction': to_json(self.transaction),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            agent = from_json(models.Agent, v['agent']),
            mounts = from_json(list[models.ShipMount], v['mounts']),
            cargo = from_json(models.ShipCargo, v['cargo']),
            transaction = from_json(models.ShipModificationTransaction, v['transaction']),
        )

# spec_name: patch-ship-nav.response
@dataclasses.dataclass
class PatchShipNav:
    """Success response for updating the nav configuration of a
    ship.
    """

    #: The navigation information of the ship.
    nav: models.ShipNav
    #: Details of the ship's fuel tanks including how much fuel was
    #: consumed during the last transit or action.
    fuel: models.ShipFuel
    events: list[models.ShipConditionEvent]

    def to_json(self) -> Json:
        v = {
            'nav': to_json(self.nav),
            'fuel': to_json(self.fuel),
            'events': to_json(self.events),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            nav = from_json(models.ShipNav, v['nav']),
            fuel = from_json(models.ShipFuel, v['fuel']),
            events = from_json(list[models.ShipConditionEvent], v['events']),
        )

# spec_name: register.response
@dataclasses.dataclass
class Register:
    """Successfully registered."""

    #: A Bearer token for accessing secured API endpoints.
    token: str
    #: Agent details.
    agent: models.Agent
    #: Faction details.
    faction: models.Faction
    #: Contract details.
    contract: models.Contract
    ships: list[models.Ship]

    def to_json(self) -> Json:
        v = {
            'token': to_json(self.token),
            'agent': to_json(self.agent),
            'faction': to_json(self.faction),
            'contract': to_json(self.contract),
            'ships': to_json(self.ships),
        }
        return v

    @classmethod
    def from_json(cls, v: Json) -> typing.Self:
        if not isinstance(v, dict):
            raise TypeError(type(v))
        return cls(
            token = from_json(str, v['token']),
            agent = from_json(models.Agent, v['agent']),
            faction = from_json(models.Faction, v['faction']),
            contract = from_json(models.Contract, v['contract']),
            ships = from_json(list[models.Ship], v['ships']),
        )
